version: "3.9"
services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 6Dd7LzJQ2EjaRKIvcNcEv7JRUvvL6uvy
      WORDPRESS_DB_NAME: wptest
    volumes:
      - wordpress:/var/www/html
    networks:
      - blogwp
    depends_on:
      - db
    # Legacy versions
    # links:
    #   - db

  db:
    container_name: mysql-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3306:3306
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - blogwp

volumes:
  wordpress:

networks:
  blogwp:
