version: "3.1"
services:
  mongo:
    image: mongo
    container_name: mongo_auth
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: yirsis
      MONGO_INITDB_ROOT_PASSWORD: BbYa0C2fOtR6
