apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-server
spec:
  selector:
    matchLabels:
      app: pma-server
  template:
    metadata:
      labels:
        app: pma-server
    spec:
      containers:
        - name: pma-server
          image: phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: rootpass
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  selector:
    app: pma-server
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
