export enum ProductsEvent {
  CREATE_PRODUCT = "CREATE_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  GET_PRODUCT = "GET_PRODUCT",
  GET_PRODUCTS = "GET_PRODUCTS",
}
